config/routes.rb
PaperTrailUi::Engine.routes.draw do
  resources :reports, only: [:index, :show]
end

app/controllers/paper_trail_ui/application_controller.rb
module PaperTrailUi
  class ApplicationController < ActionController::Base
  end
end

app/controllers/paper_trail_ui/reports_controller.rb
require 'will_paginate/array'
require 'yaml'
require_dependency "paper_trail_ui/application_controller"

module PaperTrailUi
  class ReportsController < ApplicationController
    MODEL_NAMES = PaperTrail::Version.select("DISTINCT item_type").map(&:item_type)
    EVENT_TYPES = PaperTrail::Version.select("DISTINCT event").map(&:event)
    ACTOR_NAMES = PaperTrail::Version.select("DISTINCT whodunnit").map(&:whodunnit)

    def index
      @model_names = array_to_filter_hash(MODEL_NAMES)
      @event_names = array_to_filter_hash(EVENT_TYPES)
      @actor_names = array_to_filter_hash(ACTOR_NAMES)
      @query = PaperTrail::Version.search params[:q]
      @versions = @query.result(distinct: true).paginate(page: params[:page], per_page: 100)
    end

    def show
      @version = PaperTrail::Version.find params[:id]
      @object = YAML.load(@version.object || "---") || {}
    end

    private
      def array_to_filter_hash(array)
        {"All" => ""}.merge(array.reduce({}){|a, x| a[x] = x; a})
      end
  end
end

app/helpers/paper_trail_ui/application_helper.rb
module PaperTrailUi
  module ApplicationHelper

    def row_counter_with_paging(index, options={})
      current_page = (params[options[:page_param] || :page] || 1).to_i
      per_page = options[:per_page] || WillPaginate.per_page
      ((current_page-1)*per_page)+index+1
    end
  end
end

app/views/layouts/paper_trail_ui/application.html.haml
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title PaperTrailUi
    = stylesheet_link_tag    "paper_trail_ui/application", media: "all"
    = javascript_include_tag "paper_trail_ui/application"
    = csrf_meta_tags
  %body
    = yield

app/views/paper_trail_ui/reports/_object_info_row.html.haml
%tr
  %th
    = locals[:key].try(:humanize)
  %td
    = locals[:value]

app/views/paper_trail_ui/reports/index.html.haml
.container
  %h2
    PaperTrail report
  #report.well
    = search_form_for @query, url: reports_path, html: { class: "form-horizontal" } do |f|
      .row
        .col-md-12
          .form-group
            = f.label nil, "PaperTrail object ID"
            = f.text_field :item_id_eq,                     |
              class: "span9 form-control", placeholder: "Search PaperTrail object ID" |
        .col-md-12
          .form-group
            = f.label :created_at_gteq, "Date"
            From #{f.text_field :created_at_gteq, value: @query.created_at_gteq.try(:to_date), class: "datepicker span2 form-control", data: { date_format: "yyyy-mm-dd" }}
            To #{f.text_field :created_at_lteq, value: @query.created_at_lteq.try(:to_date), class: "datepicker span2 form-control", data: { date_format: "yyyy-mm-dd" }}
          .form-group
            = f.label nil, "Search serialized object data"
            = f.text_field :object_cont,                     |
              class: "span9 form-control", placeholder: "Search serialized Object Data" |

      .row
        .col-md-4
          .form-group
            = f.label :item_type_eq, "Model Name"
            = f.select :item_type_in, @model_names, class: "form-control"
        .col-md-4
          .form-group
            = f.label :event_eq, "Event"
            = f.select :event_in, @event_names, class: "form-control"
        .col-md-4
          .form-group
            = f.label :whodunnit_eq, "Actor(whodunnit)"
            = f.select :whodunnit_in, @actor_names, class: "form-control"
      .row 
        .col-md-4 
          = f.submit "Filter", class: "btn btn-primary", id: "filter"
          = link_to "Reset", reports_path, class: "btn btn-success"
  %p
    Versions
    %b= @query.result.count

  %table.table
    %thead
      %tr
        %th #
        %th= sort_link @query, :item_type, "Model Name"
        %th ID
        %th= sort_link @query, :event, "Event"
        %th= sort_link @query, :whodunnit, "Actor"
        %th= sort_link @query, :created_at, "Created At"
        %th Object Data

    %tbody
      - @versions.each_with_index do |version, index|
        %tr
          %td= row_counter_with_paging(index)
          %td= version.item_type
          %td= version.item_id
          %td= version.event
          %td= version.whodunnit
          %td= version.created_at.to_s(:day_month_year)
          %td= link_to "View", report_path(version.id), class: "btn btn-info"
  = will_paginate @versions

app/views/paper_trail_ui/reports/show.html.haml
.container
  %h4
    = link_to "Back", url_for(:back) 
  %h2
    PaperTrail object details
  .well
    %table.table.table-condensed
      %tr
        %td
          PaperTrail ID
        %td
          = @version.id
      %tr
        %td
          Item Type
        %td
          = @version.item_type
      %tr
        %td
          Event
        %td
          = @version.event
      %tr
        %td
          Actor
        %td
          = @version.whodunnit
      %tr
        %td
          Created At
        %td
          = @version.created_at
  .row
    .col-md-12
      %h3 Details of the object in the system
      %table.table.table-condensed
        = render "object_info_row", locals: {key: "Class", value: @version.item_type}
        - @object.each do |k, v|
          = render "object_info_row", locals: {key: k, value: v}